<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes, Continue</name>
   <tag></tag>
   <elementGuidId>86c3b70f-75e0-4f4b-9a6a-74f7d84ac654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._42ft._4jy0._9kpt._4jy5._4jy1.selected._51sy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value='1'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9322465a-af8a-4bcf-b92c-43ba08110a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d3b8826b-37e0-48ac-8097-592e6adecab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _9kpt _4jy5 _4jy1 selected _51sy</value>
      <webElementGuid>8074517c-1202-4372-acd5-738845addb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ecf25288-ebfd-4496-8145-52541568fd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1e3a9036-0010-46c8-a895-94ce25c20cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes, Continue</value>
      <webElementGuid>02ddcabf-aaa7-4412-99be-eabeb23cc181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_8_GO&quot;)/button[@class=&quot;_42ft _4jy0 _9kpt _4jy5 _4jy1 selected _51sy&quot;]</value>
      <webElementGuid>71b15c57-1ad9-48d6-9c4e-ea8eccc5f539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value='1'])[2]</value>
      <webElementGuid>982c7595-b1bf-4d77-b949-a3fc7e71acc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_8_GO']/button</value>
      <webElementGuid>18bb38ae-8d3e-4c62-a547-95f697ffe1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not you?'])[1]/following::button[1]</value>
      <webElementGuid>e5f7f857-e90f-44dd-bbfd-5c5627611682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='email@gmail.com •'])[1]/following::button[1]</value>
      <webElementGuid>2310436c-3aa1-4464-8761-29c492513315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes, Continue']/parent::*</value>
      <webElementGuid>4526fbdc-dd1b-4749-a912-59086f1d618b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/form/div/button</value>
      <webElementGuid>643b3142-d372-4229-b86e-32af5fe4691a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Yes, Continue' or . = 'Yes, Continue')]</value>
      <webElementGuid>ad2b3bb0-49c4-4219-8e21-899359f8ff2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
